### ISSUE TITLE
并发数默认或设置成1，运行后都报错无效的内存地址或...

### ISSUE THREAD

**Issue by ghost** [pythonzm/sshpro#1]
报错如下：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x45cd54]

goroutine 148 [running]:
sshpro/utils/root.Connection.OutPut.func3(0xc000212190, 0x52f0028, 0xc0003523a0,
 0xc000356330)
        /usr/local/go/src/sshpro/utils/root/connect.go:92 +0xc6
created by sshpro/utils/root.Connection.OutPut
        /usr/local/go/src/sshpro/utils/root/connect.go:88 +0x3b1

**Comment by pythonzm** [comment]
我试了没问题，你执行的是什么命令，方便贴一下吗

**Comment by ghost** [comment]
就是的hostname命令，一两百的ip数

**Comment by pythonzm** [comment]
这个现象好像是随机性的，我先用--host-range参数执行了100多台机器，没有报错，然后用配置文件执行也没报错，之后又试了几次，出现过一次这个报错，我稍微修改了connect.go，把session.Stdout = &stdout放在后边了，我试了几次没有报错了，你重新拉代码编译试下？
